# Learn more about configuring your checkout UI extension:
# https://shopify.dev/api/checkout-extensions/checkout/configuration

# The version of APIs your extension will receive. Learn more:
# https://shopify.dev/docs/api/usage/versioning
api_version = "2023-10"

[[extensions]]
type = "ui_extension"
name = "Bunner"
handle = "checkout-ui-banner"

# Controls where in Shopify your extension will be injected,
# and the file that contains your extension’s source code. Learn more:
# https://shopify.dev/docs/api/checkout-ui-extensions/unstable/extension-targets-overview

#[[extensions.targeting]]
#module = "./src/Checkout.js"
#target = "purchase.checkout.block.render"
#export = "checkoutBlockRender"
#
#[[extensions.targeting]]
#module = "./src/Checkout.js"
#target = "purchase.checkout.shipping-option-list.render-before"
#export = "shippingRenderBefore"
#
#  [[customer.metafields]]
#  namespace = "checkout-shipping"
#  key = "customer_text_field"
#
#
#[[extensions.targeting]]
#module = "./src/Checkout.js"
#target = "purchase.checkout.shipping-option-list.render-after"
#export = "checkoutShippingOptionList"
#
#[[extensions.targeting]]
#module = "./src/Checkout.js"
#target = "purchase.thank-you.block.render"
#export = "checkoutThankYouBlock"

[[extensions.targeting]]
module = "./src/Checkout.js"
target = "purchase.checkout.cart-line-list.render-after"
export = "checkoutLineItem"


[extensions.capabilities]
# Gives your extension access to directly query Shopify’s storefront API.
# https://shopify.dev/docs/api/checkout-ui-extensions/unstable/configuration#api-access
api_access = true

# Gives your extension access to make external network calls, using the
# JavaScript `fetch()` API. Learn more:
# https://shopify.dev/docs/api/checkout-ui-extensions/unstable/configuration#network-access
# network_access = true

# Loads metafields on checkout resources, including the cart,
# products, customers, and more. Learn more:
# https://shopify.dev/docs/api/checkout-ui-extensions/unstable/configuration#metafields

#[[extensions.metafields]]
# namespace = "my_namespace"
# key = "my_key"

# Defines settings that will be collected from merchants installing
# your extension. Learn more:
# https://shopify.dev/docs/api/checkout-ui-extensions/unstable/configuration#settings-definition

[extensions.settings]
  [[extensions.settings.fields]]
  key = "variant_reference"
  type = "variant_reference"
  name = "variant_reference"

  [[extensions.settings.fields]]
    key = "show_button"
    type = "boolean"
    name = "Show button?"



